import os
import time

print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("~~~ Windows Activator ~~~")
print("~~~ Enterprise N Edition ~~~")
print("----------------------------------------------")
print("Do not close any dialogs that are opened self. That dialogs will activate your windows else it didn't.")
time.sleep(1.5)
print("Note: Try running terminal with adminstrator privilleges to properly activate windows. Else this activator might not work.")
time.sleep(1.5)
print("----------------------------------------------")
print("Setting things up...")
time.sleep(1.5)
print("Activating Windows...")
print("----------------------------------------------")
time.sleep(2)
os.system("slmgr /ipk WGGHN-J84D6-QYCPR-T7PJ7-X766F")
os.system("slmgr /skms kms8.msguides.com")
os.system("slmgr /ato")
print("----------------------------------------------")
print("Windows Succesfully Activated! Enjoy using Windows!")
print("If the wrapper still show on your computer, Restart your PC to take effect.")
print("Press Enter Key to close.")
print("----------------------------------------------")
input()
